services:
    api:
        container_name: translation-api
        build:
            context: .
            dockerfile: ./docker/local/Dockerfile
            target: php
            args:
                - APP_ENV=local
        environment:
            - APP_ENV=local
        working_dir: /var/www
        volumes:
            - ./site:/var/www
            - ./site/storage:/var/www/storage
        networks:
            - api_network
        depends_on:
            - database
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3308:3306
        environment:
            - MYSQL_DATABASE=translation_management
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - api_network

    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/local/nginx/mkcert:/etc/nginx/mkcert
            - ./site:/var/www
        ports:
            - "80:80"
            - "443:443"
        networks:
            - api_network
        depends_on:
            - api
volumes:
    db-data: ~

networks:
  api_network:
    driver: bridge